---
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/clouds.yaml
  gather_facts: true

  roles:
    - role: common
    - role: openstack-volume
    - role: security-group
    - role: create-instance
    - role: check_groups

 # create couchdb
- hosts: database
  vars_files:
    - host_vars/docker-config.yaml
    - host_vars/couchDB-config.yml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: common-instance
    - role: docker-volumes
    - role: docker
    - role: create-couchDB

# deploy couchdb masternode
- hosts: masternode
  vars_files:
    - host_vars/docker-config.yaml
    - host_vars/couchDB-config.yml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: deploy-couchDB

# deploy couchdb peer nodes
- hosts: workers
  vars_files:
    - host_vars/docker-config.yaml
    - host_vars/couchDB-config.yml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: check-couchDB-membership

# deploy Twitter data and Aurin data
- hosts: backend
  vars_files:
    - host_vars/docker-config.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: deploy-backend-twitter-history
    - role: deploy-backend-Aurin
    - role: deploy-backend-twitter-live

# deploy sentimental analysis application to instance 2
- hosts: masternode
  vars_files:
    - host_vars/docker-config.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: deploy-backend-sentiment

# deploy frontend applications
- hosts: frontend
  vars_files:
    - host_vars/docker-config.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: deploy-frontend