# -----------------------------------------------
# Author        = Xinyi Jin (Melody)
# Date          = 2022-05-10 23:19
# Description   = playbook to deploy backend applications (Twitter/Aurin/Sentiment)
# Version       = 2022/5/10   
# -----------------------------------------------

# get dynamic Inventory
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/clouds.yaml
  gather_facts: true
  roles:
    - role: check_groups

# deploy Twitter data and Aurin data
- hosts: backend
  vars_files:
    - host_vars/docker-config.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: deploy-backend-twitter-history
    - role: deploy-backend-Aurin
    - role: deploy-backend-twitter-live

# deploy sentimental analysis application to instance 2
- hosts: masternode
  vars_files:
    - host_vars/docker-config.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: deploy-backend-sentiment
