---
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/clouds.yaml
  gather_facts: true

  roles:
    - role: common
    - role: openstack-volume
    - role: security-group
    - role: create-instance
