# -----------------------------------------------
# Author        = Xinyi Jin (Melody)
# Date          = 2022-05-10 23:21
# Description   = playbook to deploy frontend appliation
# Version       = 2022/5/10   
# -----------------------------------------------

# get dynamic Inventory
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/clouds.yaml
  gather_facts: true
  roles:
    - role: check_groups

- hosts: frontend
  vars_files:
    - host_vars/docker-config.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: host_vars/initialisation.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: deploy-frontend